# Generated by Django 3.0.2 on 2020-05-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
